# Generated by Django 3.2.20 on 2023-08-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_message', '0002_auto_20230829_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendemailmessage',
            old_name='receiver',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='sendemailmessage',
            old_name='sender',
            new_name='sender_user',
        ),
    ]
