# Generated by Django 3.2.20 on 2023-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
