# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_promocode_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralbonus',
            name='referral_credit_points_bonus',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
