# Generated by Django 3.2.20 on 2023-09-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_cartitem'),
        ('payment', '0004_payment_final_items_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='app.order'),
        ),
    ]
