# Generated by Django 3.2.20 on 2023-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20231028_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
