# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20231113_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_items_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='items_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='promo_code_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='promo_code_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=14, unique=True),
        ),
    ]
