# Generated by Django 3.2.20 on 2023-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='is_seller_verified',
            field=models.BooleanField(default=False),
        ),
    ]
