# Generated by Django 3.2.20 on 2023-12-02 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_postfreead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfreead',
            old_name='product_name',
            new_name='ad_name',
        ),
        migrations.AddField(
            model_name='postfreead',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
