# Generated by Django 3.2.20 on 2023-12-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20231202_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfreead',
            old_name='campaign_duration',
            new_name='duration',
        ),
    ]
