# Generated by Django 3.2.20 on 2023-12-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20231202_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
