# Generated by Django 3.2.20 on 2023-12-03 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0011_alter_postfreead_ad_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPaidAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=80, null=True)),
                ('ad_category', models.CharField(blank=True, choices=[('Home Appliances', 'Home Appliances'), ('Properties', 'Properties'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Vehicles', 'Vehicles'), ('Services', 'Services'), ('Mobile Phones', 'Mobile Phones'), ('Health & Beauty', 'Health & Beauty'), ('Sports', 'Sports'), ('Jobs', 'Jobs'), ('Babies and Kids', 'Babies and Kids'), ('Agric & Food', 'Agric & Food'), ('Repairs', 'Repairs'), ('Equipment & Tools', 'Equipment & Tools'), ('CVs', 'CVs'), ('Pets', 'Pets'), ('Others', 'Others')], max_length=100, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('Washing Machine', 'Washing Machine'), ('Refrigerator', 'Refrigerator'), ('Microwave', 'Microwave'), ('Coffee Machine', 'Coffee Machine'), ('Air Conditioner', 'Air Conditioner'), ('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial Property', 'Commercial Property'), ('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Camera', 'Camera'), ('Headphones', 'Headphones'), ('Television', 'Television'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Bicycle', 'Bicycle'), ('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Electrician', 'Electrician'), ('Catering', 'Catering'), ('Tutoring', 'Tutoring'), ('iPhone', 'iPhone'), ('Samsung', 'Samsung'), ('Google Pixel', 'Google Pixel'), ('OnePlus', 'OnePlus'), ('Skincare', 'Skincare'), ('Haircare', 'Haircare'), ('Makeup', 'Makeup'), ('Fitness Equipment', 'Fitness Equipment'), ('Soccer', 'Soccer'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Golf', 'Golf'), ('IT', 'IT'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Administrative', 'Administrative'), ('Toys', 'Toys'), ('Clothing Kids', 'Clothing'), ('Strollers', 'Strollers'), ('Farm Products', 'Farm Products'), ('Processed Food', 'Processed Food'), ('Beverages', 'Beverages'), ('Electronic Repair', 'Electronic Repair'), ('Appliance Repair', 'Appliance Repair'), ('Car Repair', 'Car Repair'), ('Power Tools', 'Power Tools'), ('Hand Tools', 'Hand Tools'), ('Kitchen Tools', 'Kitchen Tools'), ('Engineering', 'Engineering'), ('Marketing CVs', 'Marketing'), ('Design', 'Design'), ('Education', 'Education'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Bird', 'Bird'), ('Others', 'Others')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, choices=[('Brand New', 'Brand New'), ('Fairly Used', 'Fairly Used')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=450, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=255, null=True)),
                ('ad_rating', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('ad_save_count', models.PositiveIntegerField(default=0, editable=False)),
                ('ad_view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('count_in_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('ad_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='./media/marketplace')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='./media/marketplace')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='./media/marketplace')),
                ('duration', models.CharField(blank=True, choices=[('0 day', '0 day'), ('1 day', '1 day'), ('2 days', '2 days'), ('3 days', '3 days'), ('5 days', '5 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks'), ('1 month', '1 month')], default='1 day', max_length=100, null=True)),
                ('duration_hours', models.DurationField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
