# Generated by Django 3.2.20 on 2023-12-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_referralbonus_referral_credit_points_bonus'),
        ('marketplace', '0013_marketplaceselleraccount_business_reg_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='ad_charges',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='postfreead',
            name='is_price_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postfreead',
            name='phone_view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='postfreead',
            name='phone_view_user_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='ad_charges',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='is_price_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='phone_view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='phone_view_user_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocode'),
        ),
    ]
