# Generated by Django 3.2.20 on 2023-12-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20231206_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfreead',
            name='ad_charges',
        ),
        migrations.AlterField(
            model_name='postpaidad',
            name='ad_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
