# Generated by Django 3.2.20 on 2023-12-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0015_auto_20231206_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaidad',
            name='image1',
            field=models.ImageField(default='./media/default_ad_photo.jpg', null=True, upload_to='./media/marketplace'),
        ),
        migrations.CreateModel(
            name='PaysofterApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paysofter_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
