# Generated by Django 3.2.20 on 2023-12-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20231207_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterapikey',
            name='is_api_key_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
