# Generated by Django 3.2.20 on 2023-12-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_auto_20231208_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postfreead',
            name='seller_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_free_ad_photo', to='marketplace.marketplacesellerphoto'),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='seller_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_paid_ad_photo', to='marketplace.marketplacesellerphoto'),
        ),
        migrations.AlterField(
            model_name='postpaidad',
            name='promo_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
