# Generated by Django 3.2.20 on 2023-12-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0019_auto_20231209_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('free_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message', to='marketplace.postfreead')),
                ('paid_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_message', to='marketplace.postpaidad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
