# Generated by Django 3.2.20 on 2023-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidad',
            name='is_auto_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
