# Generated by Django 3.2.20 on 2023-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_postpaidad_is_auto_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='is_seller_banned',
            field=models.BooleanField(default=False),
        ),
    ]
