# Generated by Django 3.2.20 on 2023-12-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20231227_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
