# Generated by Django 3.2.20 on 2023-12-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_auto_20231227_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfreead',
            name='count_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpaidad',
            name='count_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
