# Generated by Django 3.2.20 on 2023-12-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_auto_20231228_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceselleraccount',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Intl Passport', 'Intl Passport'), ('Driving License', 'Driving License'), ('Govt Issued ID', 'Govt Issued ID')], max_length=50, null=True),
        ),
    ]
