# Generated by Django 3.2.20 on 2023-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_alter_marketplaceselleraccount_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='is_ad_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='is_ad_reported',
            field=models.BooleanField(default=False),
        ),
    ]
