# Generated by Django 3.2.20 on 2023-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_auto_20231229_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidad',
            name='usd_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD')], default='USD', max_length=50, null=True),
        ),
    ]
