# Generated by Django 3.2.20 on 2023-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_postpaidad_usd_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaidad',
            name='usd_currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=50, null=True),
        ),
    ]
