# Generated by Django 3.2.20 on 2023-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message_inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessageinbox',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sendmessageinbox',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
