# Generated by Django 4.1.4 on 2023-06-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderitem_price_currency_product_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media/images/products'),
        ),
    ]
