# Generated by Django 3.2.20 on 2023-09-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
