# Generated by Django 3.2.20 on 2023-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230819_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
