# Generated by Django 3.2.20 on 2023-09-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230918_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
