# Generated by Django 3.2.20 on 2023-08-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230819_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
    ]
