# Generated by Django 3.2.20 on 2023-08-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230821_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='isPaid',
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='app.orderitem'),
        ),
    ]
