# Generated by Django 3.2.20 on 2023-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
