# Generated by Django 3.2.20 on 2023-10-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0003_chatroom_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='room_name',
        ),
    ]
