# Generated by Django 3.2.20 on 2023-10-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0004_rename_name_chatroom_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='message',
        ),
    ]
