# Generated by Django 3.2.20 on 2023-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0006_alter_chatmessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_topic',
            field=models.CharField(blank=True, choices=[('otp', 'OTP'), ('payments', 'Payments'), ('transactions', 'Transactions'), ('payouts', 'Payouts'), ('services', 'Services'), ('credit_points', 'Credit Points'), ('account_funds', 'Account Funds'), ('referrals', 'Referrals'), ('others', 'Others')], max_length=225, null=True),
        ),
    ]
