# Generated by Django 3.2.20 on 2023-11-15 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=225, null=True)),
                ('category', models.CharField(blank=True, choices=[('support', 'Support'), ('billing', 'Billing'), ('abuse', 'Abuse'), ('otp', 'OTP'), ('payments', 'Payments'), ('transactions', 'Transactions'), ('payouts', 'Payouts'), ('services', 'Services'), ('credit_points', 'Credit Points'), ('account_funds', 'Account Funds'), ('referrals', 'Referrals'), ('others', 'Others')], max_length=225, null=True)),
                ('ticket_id', models.CharField(max_length=12, null=True, unique=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('support_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_response', to='support.supportticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_response_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
