# Generated by Django 3.2.20 on 2023-10-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='subject',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=225, null=True)),
                ('category', models.CharField(blank=True, choices=[('otp', 'OTP'), ('payments', 'Payments'), ('transactions', 'Transactions'), ('payouts', 'Payouts'), ('services', 'Services'), ('credit_points', 'Credit Points'), ('account_funds', 'Account Funds'), ('referrals', 'Referrals'), ('others', 'Others')], max_length=225, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
        ),
    ]
