# Generated by Django 3.2.20 on 2023-10-10 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_auto_20231009_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='is_open',
            new_name='is_closed',
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_message_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
