# Generated by Django 3.2.20 on 2023-10-13 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0008_auto_20231013_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('support_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_response_message', to='support.supportmessage')),
                ('support_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_response', to='support.supportticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_response_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
