# Generated by Django 3.2.20 on 2023-10-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20231013_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportresponse',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
