# Generated by Django 3.2.20 on 2023-10-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_supportresponse_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='category',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, choices=[('otp', 'OTP'), ('payments', 'Payments'), ('transactions', 'Transactions'), ('payouts', 'Payouts'), ('services', 'Services'), ('credit_points', 'Credit Points'), ('account_funds', 'Account Funds'), ('referrals', 'Referrals'), ('others', 'Others')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='supportresponse',
            name='support_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_response', to='support.supportticket'),
        ),
    ]
