# Generated by Django 3.2.20 on 2023-10-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_alter_supportticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportresponse',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='modified',
        ),
    ]
