# Generated by Django 3.2.20 on 2023-11-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_auto_20231025_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
