# Generated by Django 3.2.20 on 2023-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_delete_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportresponse',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
