# Generated by Django 4.1.4 on 2023-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_reset_password_email', '0002_passwordresettoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
