# Generated by Django 4.1.4 on 2023-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
