# Generated by Django 4.1.4 on 2023-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_otp', '0002_emailotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
