# Generated by Django 4.1.4 on 2023-08-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_otp', '0003_alter_emailotp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
