# Generated by Django 3.2.20 on 2023-11-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_terms_conditions_read',
            field=models.BooleanField(default=False),
        ),
    ]
