# Generated by Django 3.2.20 on 2023-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_view_count'),
        ('user_profile', '0002_user_favorite_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_products',
            field=models.ManyToManyField(related_name='viewed_products', to='app.Product'),
        ),
    ]
