# Generated by Django 3.2.20 on 2023-12-14 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        # ('app', '0007_auto_20231118_1352'),
        ('user_profile', '0003_auto_20231124_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(editable=False, related_name='favorited_by', to='app.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='viewed_products',
            field=models.ManyToManyField(editable=False, related_name='viewed_products', to='app.Product'),
        ),
    ]
