# Generated by Django 3.2.20 on 2023-08-28 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_review_rating'),
        ('credit_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpointrequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_user', to='app.order'),
        ),
    ]
