# Generated by Django 3.2.20 on 2023-09-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('credit_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpointrequest',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_order', to='payment.payment'),
        ),
    ]
