# Generated by Django 3.2.20 on 2023-09-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('credit_point', '0002_creditpointrequest_order_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpointrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpointpayment',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_order_payment', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='creditpointpayment',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_credit_point_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpointearning',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_order_earning_payment', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='creditpointearning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_earning_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpoint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
