# Generated by Django 3.2.20 on 2023-09-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_final_items_amount'),
        ('credit_point', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpointearning',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_earnings', to='payment.payment'),
        ),
    ]
