# Generated by Django 3.2.20 on 2023-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0004_alter_creditpointearning_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpointrequest',
            name='credit_point_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
