# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0005_alter_creditpointrequest_credit_point_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpoint',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditpointearning',
            name='credit_points_earned',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditpointpayment',
            name='credit_points_earned',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditpointrequest',
            name='credit_point_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
