# Generated by Django 3.2.20 on 2023-12-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0006_auto_20231118_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpoint',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
