# Generated by Django 3.2.20 on 2023-12-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0009_buycreditpoint_sellcreditpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycreditpoint',
            name='cps_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buycreditpoint',
            name='amount',
            field=models.CharField(blank=True, choices=[('500', '500 cps for NGN 500'), ('1000', '1,000 cps for NGN 1,000'), ('5000', '5,200 cps for NGN 5,000'), ('10000', '10,800 cps for NGN 10,000'), ('15000', '16,500 cps for NGN 15,000'), ('20000', '24,000 cps for NGN 20,000'), ('60000', '60,000 cps for NGN 50,000'), ('100000', '125,000 cps for NGN 100,000'), ('250000', '255,000 cps for NGN 200,000'), ('600000', '620,000 cps for NGN 500,000'), ('1000000', '1,500,000 cps for NGN 1,000,000')], editable=False, max_length=100, null=True),
        ),
    ]
